hochmun/Kmarket_Project_2nd

- HTML/admin/index.html
- HTML/css/admin.css
- HTML/css/common.css
- HTML/index.html
2023/02/07 심규영
메인 페이지 (main/index.html) 완료
메인 페이지 CSS 완료
관리자 index.html 완료
관리자 CSS 작성중
> 2023/02/07 심규영

- HTML/css/member/member.css
- HTML/member/join.html
- HTML/member/login.html
- HTML/member/register.html
- HTML/member/registerSeller.html
- HTML/member/signup.html
> 2023-02-07 멤버 작업

- HTML/admin/index.html
- HTML/admin/product/list.html
- HTML/admin/product/register.html
- HTML/css/admin.css
- HTML/js/gnb.js
- Kmarket/build.gradle
- Kmarket/src/main/java/kr/co/kmarket/entity/UserEntity.java
- Kmarket/src/main/java/kr/co/kmarket/security/MyUserDetails.java
- Kmarket/src/main/java/kr/co/kmarket/security/SecurityConfig.java
- Kmarket/src/main/java/kr/co/kmarket/security/SecurityUserService.java
- Kmarket/src/main/resources/application.properties
2023/02/08 심규영
관리자 메인 페이지
관리자 상품 리스트 페이지
관리자 상품 등록 페이지 완료
security 추가 진행중
> 2023/02/08 심규영 html 페이지 작업 완료

- Kmarket/src/main/java/kr/co/kmarket/entity/UserEntity.java
- Kmarket/src/main/java/kr/co/kmarket/repository/UserRepo.java
- Kmarket/src/main/java/kr/co/kmarket/security/MyUserDetails.java
- Kmarket/src/main/java/kr/co/kmarket/security/SecurityConfig.java
- Kmarket/src/main/java/kr/co/kmarket/security/SecurityUserService.java
> 2023/02/08 심규영 시큐리티 기본 작업 완료

- Kmarket/log/Farmstory.log
- Kmarket/src/main/java/kr/co/kmarket/controller/MemberController.java
- Kmarket/src/main/java/kr/co/kmarket/security/SecurityConfig.java
- Kmarket/src/main/java/kr/co/kmarket/service/MemberService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/memberVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/member_pointVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/member_termsVO.java
- Kmarket/src/main/resources/templates/index.html
- Kmarket/src/main/resources/templates/member/_footer.html
- Kmarket/src/main/resources/templates/member/_header.html
- Kmarket/src/main/resources/templates/member/join.html
- Kmarket/src/main/resources/templates/member/login.html
- Kmarket/src/main/resources/templates/member/register.html
- Kmarket/src/main/resources/templates/member/registerSeller.html
- Kmarket/src/main/resources/templates/member/signupSeller.html
2023-02-08 전인준 멤버 vo,controller
> 2023-02-08 전인준 멤버 vo,controller

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaListController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/AdminDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MainDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MemberDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/ProductDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsQnaDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/CsService.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsQnaService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_Cate1VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_Cate2VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_FaqVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_NoticeVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_QnaVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/cs_cate1VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/cs_cate2VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/cs_faqVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/cs_noticeVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/cs_qnaVO.java
- Kmarket/src/main/resources/mappers/csqna.xml
- Kmarket/src/main/resources/templates/cs/index.html
- Kmarket/src/main/resources/templates/cs/qna/list.html
cs VO, DAO, Service, controller 작업.
mappers 생성
> 23/02/08 김재준 cs 기능구현 작업 시작

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaListController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaViewController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaWriteController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsQnaDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsQnaService.java
- Kmarket/src/main/resources/mappers/csqna.xml
- Kmarket/src/main/resources/templates/cs/index.html
- Kmarket/src/main/resources/templates/cs/qna/list.html
- Kmarket/src/main/resources/templates/cs/qna/write.html
- cs/qna VO, DAO, Controller 작성
- QnaArticle mapper xml 작성
현재 작업중
> 23/02/09 김재준 cs qna 기능구현

- Kmarket/src/main/java/kr/co/kmarket/controller/MainController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/admin/AdminProductController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MainDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/admin/AdminProductDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/MainService.java
- Kmarket/src/main/java/kr/co/kmarket/service/admin/AdminProductService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/productVO.java
- Kmarket/src/main/resources/mappers/adminProduct.xml
- Kmarket/src/main/resources/mappers/main.xml
- Kmarket/src/main/resources/static/js/admin/productRegister.js
- Kmarket/src/main/resources/templates/admin/product/list.html
- Kmarket/src/main/resources/templates/admin/product/register.html
- Kmarket/src/main/resources/templates/fragment/admin_fragment.html
- Kmarket/src/main/resources/templates/fragment/aside_fragment.html
- Kmarket/src/main/resources/templates/fragment/footer_fragment.html
- Kmarket/src/main/resources/templates/fragment/header_fragment.html
- Kmarket/src/main/resources/templates/fragment/main_fragment.html
- Kmarket/src/main/resources/templates/index.html
메인 작업
관리자 상품 리스트 작업
관리자 상품 등록 작업 진행중
> 2023/02/10 // 심규영 //

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaWriteController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsQnaDAO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_Cate1VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_QnaVO.java
- Kmarket/src/main/resources/mappers/csqna.xml
- Kmarket/src/main/resources/templates/cs/qna/list.html
- Kmarket/src/main/resources/templates/cs/qna/write.html
- cs/qna VO, DAO, Controller 작성
- QnaArticle mapper xml 작성
현재 작업중
> 23/02/10 김재준 cs/qna 기능구현

- Kmarket/src/main/java/kr/co/kmarket/controller/ProductController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/ProductDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/ProductService.java
- Kmarket/src/main/resources/mappers/product.xml
- Kmarket/src/main/resources/templates/fragment/aside_fragment.html
- Kmarket/src/main/resources/templates/product/list.html
- Kmarket/src/main/resources/templates/product/view.html
2023/02/10 상품 list 기능 구현 1차 완료
2023/02/10 상품 view 정보 불러오기
> 2023/02/10 이해빈 상품 view 기능 구현

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaListController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaViewController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaWriteController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsQnaDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsQnaService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_QnaVO.java
- Kmarket/src/main/resources/mappers/csqna.xml
- Kmarket/src/main/resources/templates/admin/product/list.html
- Kmarket/src/main/resources/templates/cs/qna/list.html
- Kmarket/src/main/resources/templates/cs/qna/view.html
- Kmarket/src/main/resources/templates/cs/qna/write.html
- Kmarket/src/main/resources/templates/fragment/paging_fragment.html
- cs/qna/list 구현완료
- cs/qna/write 구현완료
- 로그인 기능 생성 시 uid 연결
- qna/view 작업중 (model값이 null값으로 참조되는 상황)
> 23/02/12 김재준 cs/qna 기능구현

- Kmarket/src/main/resources/mappers/member.xml
- Kmarket/src/main/resources/static/js/Sellervalidation.js
- Kmarket/src/main/resources/static/js/validation.js
- Kmarket/src/main/resources/templates/member/register.html
- Kmarket/src/main/resources/templates/member/registerSeller.html
일반회원 - gender매핑 추가
판매자회원 - 스토리보드양식대로 회원가입때 숫자 예시 첫번째양식으로 구현 name,hp -> manager,managerhp로 데이터들어가게 수정
> 2023-02-13 전인준 member/registerSeller 유효성검사

- Kmarket/src/main/java/kr/co/kmarket/controller/ProductController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/ProductDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dto/CartDTO.java
- Kmarket/src/main/java/kr/co/kmarket/service/ProductService.java
- Kmarket/src/main/resources/mappers/member.xml
- Kmarket/src/main/resources/mappers/product.xml
- Kmarket/src/main/resources/static/js/product/cart.js
- Kmarket/src/main/resources/static/js/product/view.js
- Kmarket/src/main/resources/templates/product/cart.html
- Kmarket/src/main/resources/templates/product/order.html
- Kmarket/src/main/resources/templates/product/view.html
2023/02/13 이해빈 상품 view 기능 1차 구현 완료 - > review 기능 미구현
2023/02/13 이해빈 상품 cart 기능 구현
> 2023/02/13 이해빈 상품 view, cart 기능구현

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/faq/FaqListController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaListController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaViewController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaWriteController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsFaqDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsQnaDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsFaqService.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsQnaService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_Cate1VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_Cate2VO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_FaqVO.java
- Kmarket/src/main/resources/mappers/csFaq.xml
- Kmarket/src/main/resources/mappers/csQna.xml
- Kmarket/src/main/resources/static/js/cs/faqList.js
- Kmarket/src/main/resources/templates/cs/_cs_header.html
- Kmarket/src/main/resources/templates/cs/faq/list.html
- Kmarket/src/main/resources/templates/cs/qna/list.html
- Kmarket/src/main/resources/templates/cs/qna/view.html
- Kmarket/src/main/resources/templates/cs/qna/write.html
- cs/qna list, view, controller 기능구현 완료
- cs/index에서 qna/list로 url 입력시 'list?cate1=10' 으로 리다이렉트
- cs/qna/list 페이징 완료
- cs/qna/write 문의제목 50자 제한, 문의내용 2000자 제한
- faq/list 기능구현 시작
> 23/02/13 김재준 cs/qna 기능구현 완료, cs/faq 기능구현중

- Kmarket/src/main/java/kr/co/kmarket/controller/ProductController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/admin/AdminCsController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/ProductDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/admin/AdminCsDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dto/AdminCsListParamDTO.java
- Kmarket/src/main/java/kr/co/kmarket/service/ProductService.java
- Kmarket/src/main/java/kr/co/kmarket/service/admin/AdminCsService.java
- Kmarket/src/main/java/kr/co/kmarket/util/PagingUtil.java
- Kmarket/src/main/java/kr/co/kmarket/vo/AdminCsVo.java
- Kmarket/src/main/resources/mappers/adminCs.xml
- Kmarket/src/main/resources/mappers/product.xml
- Kmarket/src/main/resources/static/css/product.css
- Kmarket/src/main/resources/static/js/product/cart.js
- Kmarket/src/main/resources/templates/admin/cs/list.html
- Kmarket/src/main/resources/templates/fragment/admin_cs_fragment.html
- Kmarket/src/main/resources/templates/fragment/aside_fragment.html
- Kmarket/src/main/resources/templates/fragment/main_fragment.html
- Kmarket/src/main/resources/templates/product/cart.html
관리자 고객센터 리스트 페이지 페이징 처리 완료
관리자 고객센터 리스트 페이지 목록 불러오기 진행중
> 2023/02/15 // 심규영

- Kmarket/src/main/java/kr/co/kmarket/controller/ProductController.java
- Kmarket/src/main/resources/static/css/product.css
- Kmarket/src/main/resources/static/js/product/cart.js
- Kmarket/src/main/resources/static/js/product/order.js
- Kmarket/src/main/resources/templates/product/cart.html
- Kmarket/src/main/resources/templates/product/order.html
2023/02/15 이해빈 
상품 장바구니 - 전체 합계 수정
상품 주문하기 기능 구현
> 2023/02/15 이해빈 상품 주문하기 기능 구현

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/notice/NoticeListController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/notice/NoticeViewController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsNoticeDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsNoticeService.java
- Kmarket/src/main/resources/mappers/csNotice.xml
> 23/02/16 김재준 cs notice 기능구현 작업중 // Controller, DAO, Service, Mapper XML

- Kmarket/src/main/java/kr/co/kmarket/controller/MemberController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/notice/NoticeViewController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MemberDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/MemberService.java
- Kmarket/src/main/resources/mappers/member.xml
- Kmarket/src/main/resources/templates/member/search_id.html
- Kmarket/src/main/resources/templates/member/search_id_Result.html
> 2023-02-16 전인준 아이디찾기기능구현중

- Kmarket/src/main/java/kr/co/kmarket/controller/cs/faq/FaqListController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/notice/NoticeViewController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsFaqDAO.java
- Kmarket/src/main/java/kr/co/kmarket/dao/cs/CsNoticeDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsFaqService.java
- Kmarket/src/main/java/kr/co/kmarket/service/cs/CsNoticeService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_FaqVO.java
- Kmarket/src/main/java/kr/co/kmarket/vo/Cs_NoticeVO.java
- Kmarket/src/main/resources/mappers/csNotice.xml
- Kmarket/src/main/resources/templates/cs/faq/list.html
- Kmarket/src/main/resources/templates/cs/notice/view.html
> 23/02/17 김재준 notice 기능작업 완료

- Kmarket/src/main/java/kr/co/kmarket/controller/MemberController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MemberDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/MemberService.java
- Kmarket/src/main/resources/mappers/member.xml
- Kmarket/src/main/resources/templates/member/search_id.html
- Kmarket/src/main/resources/templates/member/search_id_Result.html
> 2023-02-17 전인준 아이디찾기 기능구현중

- Kmarket/src/main/java/kr/co/kmarket/controller/MemberController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MemberDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/MemberService.java
- Kmarket/src/main/resources/mappers/member.xml
- Kmarket/src/main/resources/templates/member/login.html
- Kmarket/src/main/resources/templates/member/search_id.html
- Kmarket/src/main/resources/templates/member/search_id_Result.html
- Kmarket/src/main/resources/templates/member/search_pwd_Change.html
2023-02-21 전인준 아이디찾기기능구현완료, 비밀번호찾기기능 시작
> 2023-02-21 전인준 아이디찾기기능구현완료, 비밀번호찾기기능 시작

- Kmarket/src/main/java/kr/co/kmarket/controller/MyController.java
- Kmarket/src/main/java/kr/co/kmarket/controller/cs/qna/QnaWriteController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MyDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/MyService.java
- Kmarket/src/main/java/kr/co/kmarket/vo/product_reviewVO.java
- Kmarket/src/main/resources/mappers/my.xml
- Kmarket/src/main/resources/static/js/cs/faqList.js
- Kmarket/src/main/resources/static/js/my/myQna.js
- Kmarket/src/main/resources/templates/my/review.html
- my/qna, review 비로그인 시 NullException
- my/qna, review 로그인 사용자가 작성한 글만 보이기
- my/qna 답변 출력<a>태그 선택으로 스크립트 수정
- my/review 상품명 클릭 시 해당 product/view로 새탭 열기
> 23/02/22 // 김재준 // my/qna, review 기능 작업 완료 //

- Kmarket/src/main/java/kr/co/kmarket/controller/MyController.java
- Kmarket/src/main/java/kr/co/kmarket/dao/MyDAO.java
- Kmarket/src/main/java/kr/co/kmarket/service/MyService.java
- Kmarket/src/main/resources/mappers/my.xml
- Kmarket/src/main/resources/templates/fragment/paging_fragment.html
- Kmarket/src/main/resources/templates/my/ordered.html
- Kmarket/src/main/resources/templates/my/point.html
- my/point, ordered list 구현
- 페이징 구현
- 로그인 사용자의 uid와 일치하는 테이블만 가져오도록 구현
> 23/02/22 // 김재준 my/ordered, point 기능작업 중
